In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('arhiva.txt', sep='\t',header=None)
#print(df.head(2))
arr = df.to_numpy()
#remove 1st column - data
arr = arr[:,[1,2,3,4,5,6]]
records = arr.shape[0]
#remove header
arr = arr[1:records,:]
#strings to int
df = pd.DataFrame(arr)
df = df.astype(int)
arr = df.to_numpy()
arr

array([[ 5, 13, 26, 38, 37, 25],
       [20, 32, 38, 21,  5, 11],
       [32, 27, 38, 11, 10, 29],
       ...,
       [11, 35, 25,  4, 27, 24],
       [ 3, 33, 25, 13, 17, 20],
       [ 8, 37, 12,  9,  7,  4]])

In [2]:
df=pd.read_csv('20_3_95.txt', sep=',',header=None)
print(df.head(2))
arr2 = df.to_numpy()
arr2

   0  1  2  3   4
0  1  2  3  4  10
1  5  6  7  8  14


array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 14],
       [ 9, 11, 12, 13, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  5,  9, 20],
       [ 3,  4,  6, 11, 17],
       [ 7,  8, 10, 12, 16],
       [13, 14, 15, 18, 19],
       [ 1,  2,  6, 12, 18],
       [ 3,  4,  5, 13, 16],
       [ 7,  9, 10, 11, 19],
       [ 8, 14, 15, 17, 20],
       [ 1,  2,  7, 13, 17],
       [ 3,  5,  8, 11, 18],
       [ 4,  6,  9, 14, 16]])

In [3]:
arr2

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 14],
       [ 9, 11, 12, 13, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  5,  9, 20],
       [ 3,  4,  6, 11, 17],
       [ 7,  8, 10, 12, 16],
       [13, 14, 15, 18, 19],
       [ 1,  2,  6, 12, 18],
       [ 3,  4,  5, 13, 16],
       [ 7,  9, 10, 11, 19],
       [ 8, 14, 15, 17, 20],
       [ 1,  2,  7, 13, 17],
       [ 3,  5,  8, 11, 18],
       [ 4,  6,  9, 14, 16]])

In [4]:
def matrix(comb,n,k):
    #comb = self.comb(arr,k)
    #cols = com
    #rows = math.comb(cols,k)

    z = np.zeros((comb.shape[0],n), dtype = np.int8)
    i = 0
    for c in comb:

        n1 = c[0]
        n2 = c[1]
        n3 = c[2]
        n4 = c[3]
        n5 = c[4]
        if(k==6): 
            n6 = c[5]

        z[i,n1-1] = 1
        z[i,n2-1] = 1
        z[i,n3-1] = 1
        z[i,n4-1] = 1
        z[i,n5-1] = 1
        if(k==6): 
            z[i,n6-1] = 1

        #print(i,z[i])
        i += 1

    return z

In [5]:
m1 = matrix(arr2,40,5)
m2 = matrix(arr,40,6)
intersect = m1 @ m2.T

In [6]:
intersect.shape

(15, 1942)

In [7]:
intersect

array([[0, 0, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 0, 0, 2],
       [1, 1, 1, ..., 1, 1, 2],
       ...,
       [1, 0, 0, ..., 0, 2, 1],
       [1, 2, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 2]], dtype=int8)

In [8]:
#change to 0 all values < max_intersect
intersect = np.where(intersect < 4, 0, intersect)
print("verif-selected intersections: ",np.unique(intersect))  

verif-selected intersections:  [0 4]


In [9]:
#t = np.sum(intersect,axis=1)

In [10]:
np.where(intersect> 0)

(array([ 0,  0,  1,  1,  2,  3,  4,  4,  5,  7,  9,  9,  9,  9, 10, 10, 10,
        11, 11, 13, 14]),
 array([ 357, 1261,  349, 1661, 1667, 1211,  271,  272, 1474, 1288,  961,
         985, 1306, 1607,  238,  360,  587,  186, 1634, 1831,  302]))

In [11]:
intersect[1,349]

4

In [12]:
intersect[14,302]

4

In [13]:
unique_elements, counts_elements = np.unique(intersect, return_counts=True)

In [14]:
unique_elements

array([0, 4], dtype=int8)

In [15]:
counts_elements

array([29109,    21])

In [16]:
intersect2 = m2 @ m2.T

In [17]:
intersect2

array([[6, 2, 1, ..., 1, 2, 1],
       [2, 6, 3, ..., 1, 1, 0],
       [1, 3, 6, ..., 2, 0, 0],
       ...,
       [1, 1, 2, ..., 6, 1, 1],
       [2, 1, 0, ..., 1, 6, 0],
       [1, 0, 0, ..., 1, 0, 6]], dtype=int8)

In [18]:
np.fill_diagonal(intersect2, 0)

In [40]:
intersect2.shape

(1942, 1942)

In [20]:
#change to 0 all values < max_intersect
intersect2 = np.where(intersect2 < 4, 0, intersect2)
print("verif-selected intersections: ",np.unique(intersect2)) 

verif-selected intersections:  [0 4 5]


In [22]:
hit = np.where(intersect2 > 0)

In [35]:
hit5 = np.where(intersect2 == 5)

In [34]:
hit4 = np.where(intersect2 == 4)

In [37]:
len(hit5[0])

198

In [39]:
len(hit4[0])

8314