In [25]:
import pandas as pd
import numpy as np

df=pd.read_csv('arhiva.txt', sep='\t',header=None)
#print(df.head(2))
arr = df.to_numpy()
#remove 1st column - data
arr = arr[:,[1,2,3,4,5,6]]
records = arr.shape[0]
#remove header
arr = arr[1:records,:]
#strings to int
df = pd.DataFrame(arr)
df = df.astype(int)
arr = df.to_numpy()
print(arr)
print(arr.shape)

[[ 5 13 26 38 37 25]
 [20 32 38 21  5 11]
 [32 27 38 11 10 29]
 ...
 [11 35 25  4 27 24]
 [ 3 33 25 13 17 20]
 [ 8 37 12  9  7  4]]
(1942, 6)


In [2]:
df=pd.read_csv('20_4_sigma2.txt', sep=',',header=None)
print(df.head(2))
arr2 = df.to_numpy()
#remove idx column
arr2 = arr2[:,1:6]
arr2

   0  1  2   3   4   5
0  1  8  9  10  11  12
1  2  6  7  13  14  15


array([[ 8,  9, 10, 11, 12],
       [ 6,  7, 13, 14, 15],
       [ 3,  4, 16, 17, 18],
       [ 1,  2,  5, 19, 20],
       [ 2,  8, 13, 14, 16],
       [ 4,  5,  9, 15, 19],
       [ 3,  6,  7, 12, 20],
       [ 1, 10, 11, 13, 17],
       [ 5,  6, 10, 14, 18],
       [ 1,  7,  8, 15, 18],
       [ 2,  7, 11, 17, 19],
       [ 4,  9, 11, 14, 20],
       [ 1,  3, 12, 16, 19],
       [ 2,  3, 10, 12, 15],
       [ 5,  6,  8,  9, 17],
       [ 4,  5, 12, 13, 18],
       [ 7,  9, 10, 16, 20],
       [ 3,  6,  8, 13, 19],
       [ 6, 11, 15, 16, 20],
       [ 1,  8, 12, 14, 17],
       [ 2,  9, 13, 18, 20],
       [ 1,  3,  5, 11, 20],
       [ 2,  4, 10, 14, 17],
       [ 1,  2,  9, 18, 19],
       [ 4,  5,  7,  8, 15],
       [ 1,  2,  5,  7, 11]])

In [3]:
def matrix(comb,n,k):
    #comb = self.comb(arr,k)
    #cols = com
    #rows = math.comb(cols,k)

    z = np.zeros((comb.shape[0],n), dtype = np.int8)
    i = 0
    for c in comb:

        n1 = c[0]
        n2 = c[1]
        n3 = c[2]
        n4 = c[3]
        n5 = c[4]
        if(k==6): 
            n6 = c[5]

        z[i,n1-1] = 1
        z[i,n2-1] = 1
        z[i,n3-1] = 1
        z[i,n4-1] = 1
        z[i,n5-1] = 1
        if(k==6): 
            z[i,n6-1] = 1

        #print(i,z[i])
        i += 1

    return z

In [4]:
m1 = matrix(arr2,40,5)
m2 = matrix(arr,40,6)
intersect = m1 @ m2.T

In [5]:
intersect.shape

(26, 1942)

In [6]:
intersect

array([[0, 1, 2, ..., 1, 0, 3],
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 2, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 3],
       [1, 2, 1, ..., 1, 0, 1]], dtype=int8)

In [7]:
#change to 0 all values < max_intersect
intersect = np.where(intersect < 4, 0, intersect)
print("verif-selected intersections: ",np.unique(intersect))  

verif-selected intersections:  [0 4]


In [8]:
#t = np.sum(intersect,axis=1)

In [9]:
np.where(intersect> 0)

(array([ 0,  0,  1,  1,  3,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,  9, 11,
        11, 11, 11, 12, 12, 14, 14, 15, 15, 15, 18, 19, 19, 19, 19, 20, 20,
        20, 21, 21, 22, 23, 23, 24, 25]),
 array([ 980, 1549,  416,  826,  272, 1212, 1870,  708, 1256,  335,  733,
        1501,  418,  906, 1432,  639, 1196, 1346, 1584, 1936, 1166, 1332,
        1661, 1824,  702,  836, 1863, 1159,  329,  501,  549, 1588,   85,
         771, 1216,  191,  262, 1588, 1216, 1233, 1250,  685]))

In [37]:
unique_elements, counts_elements = np.unique(intersect, return_counts=True)

In [38]:
unique_elements

array([0, 4], dtype=int8)

In [39]:
counts_elements

array([50450,    42])

In [26]:
#intersect2 = m2 @ m2.T

In [27]:
#intersect2

In [28]:
#np.fill_diagonal(intersect2, 0)

In [29]:
#intersect2.shape

In [30]:
#change to 0 all values < max_intersect
#intersect2 = np.where(intersect2 < 4, 0, intersect2)
#print("verif-selected intersections: ",np.unique(intersect2)) 

In [31]:
#hit = np.where(intersect2 > 0)

In [32]:
#hit5 = np.where(intersect2 == 5)

In [33]:
#hit4 = np.where(intersect2 == 4)

In [34]:
#len(hit5[0])

In [35]:
#len(hit4[0])